// app/golfers.ts
export interface Golfer {
  name: string;
  odds: number;
}

export const GOLFER_DATA: Golfer[] = [
 { name: "Scottie Scheffler", odds: 3 },
  { name: "Rory McIlroy", odds: 7 },
  { name: "Bryson DeChambeau", odds: 12 },
  { name: "Jon Rahm", odds: 16 },
  { name: "Xander Schauffele", odds: 16 },
  { name: "Tommy Fleetwood", odds: 18 },
  { name: "Ludvig Aberg", odds: 22 },
  { name: "Justin Rose", odds: 25 },
  { name: "Collin Morikawa", odds: 28 },
  { name: "Patrick Reed", odds: 28 },
  { name: "Hideki Matsuyama", odds: 30 },
  { name: "Cameron Young", odds: 34 },
  { name: "Viktor Hovland", odds: 34 },
  { name: "Brooks Koepka", odds: 35 },
  { name: "Jordan Spieth", odds: 40 },
  { name: "Patrick Cantlay", odds: 40 },
  { name: "Justin Thomas", odds: 45 },
  { name: "Tyrrell Hatton", odds: 45 },
  { name: "Robert MacIntyre", odds: 50 },
  { name: "Russell Henley", odds: 50 },
  { name: "Ben Griffin", odds: 50 },
  { name: "Shane Lowry", odds: 55 },
  { name: "Matt Fitzpatrick", odds: 55 },
  { name: "Min Woo Lee", odds: 55 },
  { name: "Si Woo Kim", odds: 60 },
  { name: "Sam Burns", odds: 60 },
  { name: "Cameron Smith", odds: 60 },
  { name: "Corey Conners", odds: 60 },
  { name: "Akshay Bhatia", odds: 60 },
  { name: "Jason Day", odds: 65 },
  { name: "Max Homa", odds: 65 },
  { name: "Sepp Straka", odds: 70 },
  { name: "Wyndham Clark", odds: 80 },
  { name: "J.J. Spaun", odds: 80 },
  { name: "Harris English", odds: 90 },
  { name: "Sungjae Im", odds: 90 },
  { name: "Dustin Johnson", odds: 90 },
  { name: "Alexander Noren", odds: 100 },
  { name: "Maverick McNealy", odds: 100 },
  { name: "Brian Harman", odds: 100 },
  { name: "Nicolai Hojgaard", odds: 100 },
  { name: "Sergio Garcia", odds: 100 },
  { name: "Ryan Gerard", odds: 110 },
  { name: "Marco Penge", odds: 110 },
  { name: "Keegan Bradley", odds: 120 },
  { name: "Ryan Fox", odds: 120 },
  { name: "Adam Scott", odds: 120 },
  { name: "Aaron Rai", odds: 130 },
  { name: "Rasmus Neergaard-Petersen", odds: 130 },
  { name: "Harry Hall", odds: 130 },
  { name: "John Keefer", odds: 130 },
  { name: "Tom McKibbin", odds: 140 },
  { name: "Tiger Woods", odds: 175 },
  { name: "Sam Stevens", odds: 150 },
  { name: "Kurt Kitayama", odds: 150 },
  { name: "Rasmus Hojgaard", odds: 150 },
  { name: "Carlos Ortiz", odds: 150 },
  { name: "Phil Mickelson", odds: 200 },
  { name: "Andrew Novak", odds: 200 },
  { name: "Michael Kim", odds: 200 },
  { name: "Jacob Bridgeman", odds: 200 },
  { name: "Max Greyserman", odds: 250 },
  { name: "Aldrich Potgieter", odds: 250 },
  { name: "Nick Taylor", odds: 250 },
  { name: "Bubba Watson", odds: 250 },
  { name: "Davis Riley", odds: 300 },
  { name: "Kristoffer Reitan", odds: 300 },
  { name: "Charl Schwartzel", odds: 350 },
  { name: "Michael Brennan", odds: 400 },
  { name: "Brian Campbell", odds: 400 },
  { name: "Zach Johnson", odds: 400 },
  { name: "Angel Cabrera", odds: 500 },
  { name: "Danny Willett", odds: 500 },
  { name: "Fred Couples", odds: 1000 },
  { name: "Mike Weir", odds: 1000 },
  { name: "Vijay Singh", odds: 1000 },
  { name: "Naoyuki Kataoka", odds: 1000 },
  { name: "Brandon Holtz (a)", odds: 1000 },
  { name: "Ethan Fang (a)", odds: 1000 },
  { name: "Fifa Laopakdee (a)", odds: 1000 },
  { name: "Jackson Herrington (a)", odds: 1000 },
  { name: "Mason Howell (a)", odds: 1000 },
  { name: "Mateo Pulcini (a)", odds: 1000 },
  { name: "Jose Maria Olazabal", odds: 2000 }
]; //



