export interface Golfer {
  name: string;
  points: number; // Changed from odds to points
}

export const GOLFER_DATA: Golfer[] = [
  { name: "Scottie Scheffler", points: 3 },
  { name: "Rory McIlroy", points: 7 },
  { name: "Bryson DeChambeau", points: 12 },
  { name: "Jon Rahm", points: 16 },
  { name: "Xander Schauffele", points: 16 },
  { name: "Tommy Fleetwood", points: 18 },
  { name: "Ludvig Aberg", points: 22 },
  { name: "Justin Rose", points: 25 },
  { name: "Collin Morikawa", points: 28 },
  { name: "Patrick Reed", points: 28 },
  { name: "Hideki Matsuyama", points: 30 },
  { name: "Cameron Young", points: 34 },
  { name: "Viktor Hovland", points: 34 },
  { name: "Brooks Koepka", points: 35 },
  { name: "Jordan Spieth", points: 40 },
  { name: "Patrick Cantlay", points: 40 },
  { name: "Justin Thomas", points: 45 },
  { name: "Tyrrell Hatton", points: 45 },
  { name: "Robert MacIntyre", points: 50 },
  { name: "Russell Henley", points: 50 },
  { name: "Ben Griffin", points: 50 },
  { name: "Shane Lowry", points: 55 },
  { name: "Matt Fitzpatrick", points: 55 },
  { name: "Min Woo Lee", points: 55 },
  { name: "Si Woo Kim", points: 60 },
  { name: "Sam Burns", points: 60 },
  { name: "Cameron Smith", points: 60 },
  { name: "Corey Conners", points: 60 },
  { name: "Akshay Bhatia", points: 60 },
  { name: "Jason Day", points: 65 },
  { name: "Max Homa", points: 65 },
  { name: "Sepp Straka", points: 70 },
  { name: "Wyndham Clark", points: 80 },
  { name: "J.J. Spaun", points: 80 },
  { name: "Harris English", points: 90 },
  { name: "Sungjae Im", points: 90 },
  { name: "Dustin Johnson", points: 90 },
  { name: "Alexander Noren", points: 100 },
  { name: "Maverick McNealy", points: 100 },
  { name: "Brian Harman", points: 100 },
  { name: "Nicolai Hojgaard", points: 100 },
  { name: "Sergio Garcia", points: 100 },
  { name: "Ryan Gerard", points: 110 },
  { name: "Marco Penge", points: 110 },
  { name: "Keegan Bradley", points: 120 },
  { name: "Ryan Fox", points: 120 },
  { name: "Adam Scott", points: 120 },
  { name: "Aaron Rai", points: 130 },
  { name: "Rasmus Neergaard-Petersen", points: 130 },
  { name: "Harry Hall", points: 130 },
  { name: "John Keefer", points: 130 },
  { name: "Tom McKibbin", points: 140 },
  { name: "Tiger Woods", points: 175 },
  { name: "Sam Stevens", points: 150 },
  { name: "Kurt Kitayama", points: 150 },
  { name: "Rasmus Hojgaard", points: 150 },
  { name: "Carlos Ortiz", points: 150 },
  { name: "Phil Mickelson", points: 200 },
  { name: "Andrew Novak", points: 200 },
  { name: "Michael Kim", points: 200 },
  { name: "Jacob Bridgeman", points: 200 },
  { name: "Max Greyserman", points: 250 },
  { name: "Aldrich Potgieter", points: 250 },
  { name: "Nick Taylor", points: 250 },
  { name: "Bubba Watson", points: 250 },
  { name: "Davis Riley", points: 300 },
  { name: "Kristoffer Reitan", points: 300 },
  { name: "Charl Schwartzel", points: 350 },
  { name: "Michael Brennan", points: 400 },
  { name: "Brian Campbell", points: 400 },
  { name: "Zach Johnson", points: 400 },
  { name: "Angel Cabrera", points: 500 },
  { name: "Danny Willett", points: 500 },
  { name: "Fred Couples", points: 1000 },
  { name: "Mike Weir", points: 1000 },
  { name: "Vijay Singh", points: 1000 },
  { name: "Naoyuki Kataoka", points: 1000 },
  { name: "Brandon Holtz (a)", points: 1000 },
  { name: "Ethan Fang (a)", points: 1000 },
  { name: "Fifa Laopakdee (a)", points: 1000 },
  { name: "Jackson Herrington (a)", points: 1000 },
  { name: "Mason Howell (a)", points: 1000 },
  { name: "Mateo Pulcini (a)", points: 1000 },
  { name: "Jose Maria Olazabal", points: 2000 }
];